# Generated by Django 3.1.1 on 2020-11-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categorys',
        ),
        migrations.AddField(
            model_name='listing',
            name='categorys',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
