# Generated by Django 3.1.1 on 2020-09-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
