# Generated by Django 3.1.1 on 2020-11-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201129_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categorys',
            field=models.CharField(max_length=64),
        ),
    ]
