# Generated by Django 3.1.1 on 2020-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200907_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='userses', to='auctions.listing'),
        ),
    ]
