# Generated by Django 3.1.1 on 2020-11-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201130_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categorys',
        ),
    ]
