# Generated by Django 3.1.1 on 2020-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categor',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
