# Generated by Django 3.1.1 on 2020-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_categor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categor',
            field=models.CharField(max_length=64),
        ),
    ]
