# Generated by Django 3.1.1 on 2020-11-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201130_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categor',
        ),
        migrations.AddField(
            model_name='listing',
            name='categor',
            field=models.ManyToManyField(blank=True, related_name='categorys', to='auctions.category'),
        ),
    ]
