# Generated by Django 3.1.1 on 2020-11-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201130_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
