# Generated by Django 3.1.1 on 2020-12-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categor',
        ),
    ]
