# Generated by Django 3.1.1 on 2020-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201201_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categorys',
            field=models.CharField(max_length=64),
        ),
    ]
