# Generated by Django 3.1.1 on 2020-12-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201202_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categorys',
        ),
        migrations.AddField(
            model_name='category',
            name='list_category',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.listing'),
        ),
    ]
