# Generated by Django 3.1.1 on 2020-12-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201203_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listcategory',
        ),
        migrations.AddField(
            model_name='listing',
            name='categorys',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
