# Generated by Django 3.1.1 on 2020-12-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201203_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
    ]
