# Generated by Django 3.1.1 on 2020-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('no_active', 'No Active')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
