# Generated by Django 3.1.1 on 2020-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201205_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('no_active', 'No Active')], max_length=10),
        ),
    ]
