# Generated by Django 3.1.1 on 2020-12-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201213_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('listings', models.ManyToManyField(blank=True, related_name='listing_add', to='auctions.listing')),
            ],
        ),
    ]
