# Generated by Django 3.1.1 on 2020-12-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201216_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
