# Generated by Django 3.1.1 on 2020-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201216_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
