# Generated by Django 3.1.1 on 2020-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201217_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listing_bided', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
