# Generated by Django 3.1.1 on 2020-12-19 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201219_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_name',
        ),
        migrations.AddField(
            model_name='bids',
            name='user_name',
            field=models.ManyToManyField(related_name='user_bider', to=settings.AUTH_USER_MODEL),
        ),
    ]
