# Generated by Django 3.1.1 on 2020-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20201220_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='bid',
        ),
    ]
