# Generated by Django 3.1.1 on 2020-12-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201220_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_name',
        ),
        migrations.AddField(
            model_name='bids',
            name='user_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
