# Generated by Django 3.1.1 on 2020-12-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20201220_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listings',
        ),
    ]
