# Generated by Django 3.1.1 on 2020-12-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_remove_bids_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
