# Generated by Django 3.1.1 on 2020-12-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_bids_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
